"""Export the Flow page's ladder as a TradingView Pine indicator.

Pine cannot fetch external data, so the whole snapshot travels as ONE string: baked
in as the default of a text input at export time, and rewritten in place afterwards
by flow_push.py. The script stamps the pull time on the chart and warns once it is old.

Each export overwrites the "current" file in 02 PineScripts/ (the one to paste) and
also keeps a dated copy under 07 System/lse/output/, so no snapshot is ever lost.
"""
import subprocess
from datetime import datetime
from zoneinfo import ZoneInfo

from config import TRADING_DIR

WORKFLOW = TRADING_DIR
CURRENT_PINE_PATH = WORKFLOW / "02 PineScripts" / "(C) Options Flow Ladder.pine"
RUNS_DIR = WORKFLOW / "07 System" / "lse" / "output"
CT = ZoneInfo("America/Chicago")

PINE_TEMPLATE = """// (C) Options Flow Ladder -- today's QQQ options volume / premium per strike, drawn as a
// ladder to the right of price: puts extend LEFT of the spine, calls extend RIGHT.
// Generated by Icarus (Flow page -> Export Pine) from London Strategic Edge data.
//
// This is TRADED VOLUME, not open interest. It is NOT gamma exposure and will not match
// the GEX Profile Bands or TWB.
//
// How it updates: Pine cannot fetch data, so every number lives in ONE text input ("Data").
// Its default is the snapshot baked in below, so a plain paste works on its own. With
// "Push to chart" on, Icarus rewrites that input every minute through TradingView
// Desktop's debug port -- the script itself is never re-saved. The pull time is stamped on
// the chart and turns orange once the numbers are old.
//@version=6
indicator("Options Flow Ladder (C)", shorttitle="Flow Ladder", overlay=true, max_boxes_count=500, max_labels_count=500)

// ── DATA (generated) ─────────────────────────────────────────────────────────────
// label | pull time (ms) | NQ/QQQ ratio | strike spacing | strike,callVol,putVol,callPrem,putPrem ; ... | lower,upper,ivCall,ivPut
// The last field is the IV Walls zone and may be empty. It was ADDED after the first release:
// the ladder reads fields 0-4 and ignores anything beyond, so an older copy of this script on
// a chart keeps working against a newer snapshot rather than erroring.
//<<DATA>>
// ── end DATA ─────────────────────────────────────────────────────────────────────

grpV = "Ladder"
metric         = input.string("Both", "Show", options=["Both", "Volume", "Premium"], group=grpV,
     tooltip="Both = two separate ladders side by side: VOLUME first, PREMIUM to its right. Each is scaled to its own biggest bar, so compare their shapes, not their sizes.")
lad_offset     = input.int(20,  "Offset right of last bar (bars)", minval=0, maxval=200, group=grpV)
lad_width      = input.int(40,  "Width of each side (bars)",       minval=5, maxval=140, group=grpV)
min_pct        = input.float(1.0, "Hide a side under this % of the biggest bar", minval=0, maxval=100, step=0.5, group=grpV)
show_text      = input.bool(true, "Show values",                   group=grpV)
show_stamp     = input.bool(true, "Show pull time / stale warning", group=grpV)
stale_min      = input.int(30,  "Warn when older than (minutes)",  minval=1, group=grpV)
ratio_override = input.float(0.0, "Chart/QQQ ratio override (0 = use generated)", minval=0, group=grpV,
     tooltip="Generated ratio = NQ futures price / QQQ price at pull time. Override if the ladder sits off the strikes you expect.")
grpS = "Style"
col_put  = input.color(#cf7f97, "Puts",  group=grpS)
col_call = input.color(#82b871, "Calls", group=grpS)
// Declared LAST on purpose: input ids are positional, so appending here never shifts a saved setting.
data_in  = input.text_area(GEN_DATA, "Data (Icarus fills this - do not edit)", group="Data")
// Added after the Data input on purpose: declaring it any earlier would shift Data's id on charts
// that already have this script, and the saved snapshot string would land in the wrong input.
lad_gap  = input.int(12, "Gap between the two ladders (bars)", minval=0, maxval=100, group=grpV)
// Appended here for the same reason lad_gap was: input ids are POSITIONAL, so a new input
// declared above "Data" shifts its id on every chart that already has this script, and the
// pushed snapshot then lands in the wrong input. New inputs always go at the bottom.
grpW = "IV Walls"
show_walls = input.bool(true, "Show IV Walls", group=grpW,
     tooltip="The next session's 90% containment zone from its option board's side-specific IV. Not a support/resistance level - it is a statistical claim about range, graded daily in Icarus.")
walls_back = input.int(60, "Extend left of last bar (bars)", minval=0, maxval=500, group=grpW)

f_fmt(v, is_prem) =>
    s = v >= 1e9 ? str.tostring(v / 1e9, "#.00") + "B" : v >= 1e6 ? str.tostring(v / 1e6, "#.0") + "M" : v >= 1e3 ? str.tostring(v / 1e3, "#") + "k" : str.tostring(v, "#")
    is_prem ? "$" + s : s

is_qqq_chart = str.contains(str.upper(syminfo.ticker), "QQQ")
show_v = metric != "Premium"
show_p = metric != "Volume"
both   = show_v and show_p

var box[]   B = array.new<box>()
var label[] L = array.new<label>()
var line[]  LN = array.new<line>()

// One side of one strike on one ladder. dir = -1 draws PUTS leftward from the spine, +1 draws CALLS rightward.
f_side(spine, w, dir, kc, half, v, vmax, col, is_prem, tip) =>
    pct = v / vmax * 100
    if pct >= min_pct
        x = spine + dir * math.max(1, math.round(pct / 100 * w))
        array.push(B, box.new(math.min(spine, x), kc + half, math.max(spine, x), kc - half, border_color=na, bgcolor=color.new(col, 25), xloc=xloc.bar_index))
        if show_text
            array.push(L, label.new(x, kc, f_fmt(v, is_prem), xloc=xloc.bar_index, style=dir < 0 ? label.style_label_right : label.style_label_left, color=color(na), textcolor=col, size=size.tiny, tooltip=tip))

// Wiped and rebuilt on the last bar only, so history accumulates nothing.
if barstate.islast
    for b in B
        box.delete(b)
    array.clear(B)
    for l in L
        label.delete(l)
    array.clear(L)
    for ln in LN
        line.delete(ln)
    array.clear(LN)

    parts = str.split(data_in, "|")
    if array.size(parts) >= 5
        gen_label = array.get(parts, 0)
        gen_ts    = str.tonumber(array.get(parts, 1))
        gen_ratio = str.tonumber(array.get(parts, 2))
        gen_step  = str.tonumber(array.get(parts, 3))
        rows      = str.split(array.get(parts, 4), ";")
        // On a QQQ chart the strikes are already chart prices; anywhere else (MNQ/NQ) scale them.
        ratio = ratio_override > 0 ? ratio_override : is_qqq_chart ? 1.0 : gen_ratio

        // Pass 1: parse every row and find the biggest bar of each kind, which sets each scale.
        ks  = array.new_float()
        cvs = array.new_float()
        pvs = array.new_float()
        cps = array.new_float()
        pps = array.new_float()
        vmax_v = 1.0
        vmax_p = 1.0
        for row in rows
            f = str.split(row, ",")
            if array.size(f) >= 5
                array.push(ks,  str.tonumber(array.get(f, 0)))
                array.push(cvs, str.tonumber(array.get(f, 1)))
                array.push(pvs, str.tonumber(array.get(f, 2)))
                array.push(cps, str.tonumber(array.get(f, 3)))
                array.push(pps, str.tonumber(array.get(f, 4)))
                vmax_v := math.max(vmax_v, array.get(cvs, array.size(cvs) - 1), array.get(pvs, array.size(pvs) - 1))
                vmax_p := math.max(vmax_p, array.get(cps, array.size(cps) - 1), array.get(pps, array.size(pps) - 1))

        // Pass 2: draw.
        n = array.size(ks)
        if n > 0
            // TradingView cannot draw more than 500 bars into the future; with two ladders the
            // width is quietly narrowed so the far edge of the second one always fits.
            w = both ? math.min(lad_width, math.max(5, math.floor((480 - lad_offset - lad_gap) / 4))) : lad_width
            spine_v = bar_index + lad_offset + w
            spine_p = both ? spine_v + 2 * w + lad_gap : spine_v
            half    = gen_step * ratio * 0.4
            top     = array.max(ks) * ratio + gen_step * ratio * 1.5
            for i = 0 to n - 1
                k  = array.get(ks, i)
                kc = k * ratio
                tip = "QQQ " + str.tostring(k, "#.##") + "\\nputs  " + f_fmt(array.get(pvs, i), false) + " / " + f_fmt(array.get(pps, i), true) + "\\ncalls " + f_fmt(array.get(cvs, i), false) + " / " + f_fmt(array.get(cps, i), true)
                if show_v
                    f_side(spine_v, w, -1, kc, half, array.get(pvs, i), vmax_v, col_put,  false, tip)
                    f_side(spine_v, w,  1, kc, half, array.get(cvs, i), vmax_v, col_call, false, tip)
                if show_p
                    f_side(spine_p, w, -1, kc, half, array.get(pps, i), vmax_p, col_put,  true, tip)
                    f_side(spine_p, w,  1, kc, half, array.get(cps, i), vmax_p, col_call, true, tip)
            // A name over each ladder, so the two are never mistaken for each other.
            if both
                array.push(L, label.new(spine_v, top, "VOLUME",  xloc=xloc.bar_index, style=label.style_none, textcolor=color.white, size=size.small))
                array.push(L, label.new(spine_p, top, "PREMIUM", xloc=xloc.bar_index, style=label.style_none, textcolor=color.white, size=size.small))

            if show_stamp
                age_min = (timenow - gen_ts) / 60000.0
                is_stale = age_min > stale_min
                stamp = gen_label + (is_stale ? "\\nSTALE: " + str.tostring(age_min, "#") + " min old" : "")
                array.push(L, label.new(math.round((spine_v + spine_p) / 2), top + gen_step * ratio * (both ? 2.0 : 0.0), stamp, xloc=xloc.bar_index, style=label.style_label_down, color=color.new(is_stale ? color.orange : color.gray, 40), textcolor=color.white, size=size.small))

        // ── IV WALLS ───────────────────────────────────────────────────────────────
        // The next session's 90% containment zone, from that board's side-specific IV:
        //   upper = spot * exp(+1.55 * ivCall / sqrt(252))
        //   lower = spot * exp(-1.85 * ivPut  / sqrt(252))
        // The multipliers are EMPIRICAL, not Gaussian - a symmetric 1.645 contained only
        // 89.2% of days over 501, and its misses ran 39 downside to 16 upside. Both walls
        // arrive already computed; this only draws them. See docs/(C) iv-walls-design.md.
        if show_walls and array.size(parts) >= 6
            wf = str.split(array.get(parts, 5), ",")
            if array.size(wf) >= 4
                w_lo  = str.tonumber(array.get(wf, 0)) * ratio
                w_hi  = str.tonumber(array.get(wf, 1)) * ratio
                w_ivc = str.tonumber(array.get(wf, 2))
                w_ivp = str.tonumber(array.get(wf, 3))
                if not na(w_lo) and not na(w_hi)
                    x1 = bar_index - walls_back
                    x2 = bar_index + lad_offset
                    array.push(B, box.new(x1, w_hi, x2, w_lo, border_color=na, bgcolor=color.new(color.gray, 94), xloc=xloc.bar_index))
                    array.push(LN, line.new(x1, w_hi, x2, w_hi, xloc=xloc.bar_index, color=col_call, width=2))
                    array.push(LN, line.new(x1, w_lo, x2, w_lo, xloc=xloc.bar_index, color=col_put,  width=2))
                    array.push(L, label.new(x2, w_hi, "IV Wall " + str.tostring(w_hi, format.mintick) + "  call IV " + str.tostring(w_ivc * 100, "#.00") + "% x 1.55", xloc=xloc.bar_index, style=label.style_label_left, color=color(na), textcolor=col_call, size=size.small))
                    array.push(L, label.new(x2, w_lo, "IV Wall " + str.tostring(w_lo, format.mintick) + "  put IV "  + str.tostring(w_ivp * 100, "#.00") + "% x 1.85", xloc=xloc.bar_index, style=label.style_label_left, color=color(na), textcolor=col_put,  size=size.small))
"""

# Pine strings cap at 4,096 characters, and the whole snapshot travels as one string.
MAX_DATA_CHARS = 4000


def walls_field(walls):
    """The sixth field: lower,upper,ivCall,ivPut - empty when there are no usable walls.

    Always emitted, even empty, so the field count is stable and the Pine side can test
    array.size(parts) >= 6 rather than guessing.
    """
    if not walls or not walls.get("ok"):
        return ""
    return f"{walls['lower']:.2f},{walls['upper']:.2f},{walls['iv_call']:.4f},{walls['iv_put']:.4f}"


def build_flow_data(flow, now=None, walls=None):
    # `walls` is appended rather than inserted before `now` for the same reason the Pine
    # inputs are: existing callers pass `now` positionally, and inserting would silently
    # rebind their argument.
    """The one-string snapshot the Pine script parses: header fields, then a row per strike."""
    if not flow.get("nq"):
        raise ValueError("No NQ price available, so strikes cannot be mapped to the chart. Try again in a minute.")
    now = now or datetime.now(CT)
    rows = sorted(flow["rows"], key=lambda r: r["strike"])
    strikes = [r["strike"] for r in rows]
    step = min((b - a for a, b in zip(strikes, strikes[1:])), default=1.0)
    label = f"{flow['underlying']} flow {flow['expiry']} - pulled {now.strftime('%-I:%M %p CT')}"
    header = f"{label}|{int(now.timestamp() * 1000)}|{flow['nq'] / flow['spot']:.4f}|{step:g}|"

    def body(rs):
        return ";".join(f"{r['strike']:g},{r['call_vol']:.0f},{r['put_vol']:.0f},{r['call_prem']:.0f},{r['put_prem']:.0f}" for r in rs)

    # The walls are counted against the cap BEFORE trimming, and are never what gets cut:
    # they are ~30 characters and they are the one part of the payload with no redundancy.
    tail = "|" + walls_field(walls)
    # Too long for one Pine string: drop the far strikes, outermost first, never the middle.
    while len(header) + len(body(rows)) + len(tail) > MAX_DATA_CHARS and len(rows) > 2:
        rows = rows[1:-1]
    return header + body(rows) + tail


def build_flow_pine(flow, now=None, walls=None):
    """Pine source for one flow snapshot (the dict flow.get_options_flow() returns)."""
    return PINE_TEMPLATE.replace("//<<DATA>>", f'GEN_DATA = "{build_flow_data(flow, now, walls)}"')


def export_flow_pine(flow, walls=None):
    """Write the current + dated .pine files and put the source on the clipboard."""
    now = datetime.now(CT)
    source = build_flow_pine(flow, now, walls)
    run_dir = RUNS_DIR / f"{now.strftime('%Y-%m-%d_%H%M%S')}_pine"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / CURRENT_PINE_PATH.name).write_text(source)
    CURRENT_PINE_PATH.write_text(source)
    copied = True
    try:
        subprocess.run(["pbcopy"], input=source.encode(), check=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        copied = False
    return {"path": str(CURRENT_PINE_PATH), "strikes": len(flow["rows"]), "copied": copied}
