"""Export the Flow page's GEX Walls as a TradingView Pine indicator.

Pine cannot fetch external data, so the whole snapshot travels as ONE string: baked in
as the default of a text input at export time, and rewritten in place afterwards by
freeflow_push.py. Same mechanism as flow_pine.py's ladder export - see that file for the
"one input, positional field parsing, append-only inputs" rationale. This is a SEPARATE
script/study ("GEX Walls (C)", not "Options Flow Ladder (C)") on purpose: see design.md
decision 7 - a bug here must never be able to touch the ladder's push.

Five independently-toggleable groups (decision 8): Signed-Flow GEX, Settlement-OI GEX,
and Estimated-OI GEX each get their own show switch rather than one combined "GEX"
toggle, plus Vanna Walls and Charm Zones. Toggling a group only changes what is DRAWN -
every group's data travels in the payload regardless of which are currently shown.

Each export overwrites the "current" file in 02 PineScripts/ (the one to paste) and also
keeps a dated copy under 07 System/freeflow/output/, so no snapshot is ever lost.
"""
import subprocess
from datetime import datetime
from zoneinfo import ZoneInfo

from config import TRADING_DIR

WORKFLOW = TRADING_DIR
CURRENT_PINE_PATH = WORKFLOW / "02 PineScripts" / "(C) GEX Walls.pine"
RUNS_DIR = WORKFLOW / "07 System" / "freeflow" / "output"
CT = ZoneInfo("America/Chicago")

PINE_TEMPLATE = """// (C) GEX Walls -- FreeFlow's dealer gamma/vanna/charm exposure, drawn as levels on the
// chart. Generated by Icarus (Flow page -> GEX Walls -> Export Pine) from FreeFlow.
//
// Three independent GEX methodologies (each can disagree - that's the point of having
// three): Signed-Flow (today's inferred dealer positioning from classified trades),
// Settlement OI (official, exchange-published), Estimated OI (intraday estimate, usually
// unavailable/calibrating). Plus Vanna Walls (dealer vanna-driven hedging levels) and
// Charm Zones (dealer charm-driven overnight/into-expiry drift levels). Every group has
// its own Show toggle below, so any one layer can be isolated or any subset combined.
//
// Reading it: colour = ROLE (red call wall / resistance, green put wall / support, blue
// gamma flip, orange vol trigger), matching TWB's GEX convention. Line STYLE = which
// methodology produced it: Signed-Flow solid, Settlement-OI dashed, Estimated-OI dotted.
// Walls are drawn heavier than flips and triggers.
//
// Conversion: the levels are QQQ strikes. The chart/cash ratio is MEASURED LIVE off the
// cash symbol (request.security + smoothing), the way FreeFlow's own indicator does it,
// rather than frozen at pull time - the futures/cash basis drifts through the session, so
// a frozen ratio slowly walks the levels off. The payload's ratio is only a fallback.
//
// How it updates: Pine cannot fetch data, so every number lives in ONE text input ("Data").
// Its default is the snapshot baked in below, so a plain paste works on its own. With
// "Push to chart" on, Icarus rewrites that input every minute through TradingView
// Desktop's debug port -- the script itself is never re-saved. The pull-time stamp is off
// by default; switch it on under Style to see the age / stale warning.
//@version=6
indicator("GEX Walls (C)", shorttitle="GEX Walls", overlay=true, max_lines_count=60, max_labels_count=60)

// ── DATA (generated) ─────────────────────────────────────────────────────────────
// label | pull time (ms) | fallback ratio | SF | OI | EOI | vanna | charm
// Each of SF / OI / EOI is: status,callWall,putWall,gammaFlip,volTrigger,maxPain,
//                           callStrength,putStrength,regime(LONG|SHORT)
// vanna is: callWall,putWall,flip - charm is: positiveZone,negativeZone,flip
// A status of "unavailable"/"calibrating" carries empty level fields rather than zeros -
// the Pine side treats a blank field as "nothing to draw", never as a level of zero.
//<<DATA>>
// ── end DATA ─────────────────────────────────────────────────────────────────────

grpG = "Groups"
show_sf     = input.bool(true,  "Signed-Flow GEX",    group=grpG, tooltip="Today's inferred dealer positioning from classified trades. Drawn SOLID.")
show_oi     = input.bool(true,  "Settlement-OI GEX",  group=grpG, tooltip="Official, exchange-published open interest. Drawn DASHED.")
show_eoi    = input.bool(false, "Estimated-OI GEX",   group=grpG, tooltip="Intraday OI estimate - usually unavailable/calibrating under FreeFlow's current rollout. Drawn DOTTED. Off by default; switch on per session once it's actually healthy.")
show_vanna  = input.bool(true,  "Vanna Walls",        group=grpG, tooltip="Dealer vanna-driven hedging levels - where dealers are forced to hedge on an IV move, not a price move.")
show_charm  = input.bool(true,  "Charm Zones",        group=grpG, tooltip="Dealer charm-driven overnight / into-expiry drift levels.")
show_walls_only = input.bool(false, "Walls only (hide flip / trigger)", group=grpG,
     tooltip="Drops the gamma-flip, vol-trigger and max-pain lines from every methodology, leaving just the call/put walls. The fastest way to declutter when several models are on at once.")
show_maxpain = input.bool(true, "Max Pain", group=grpG, tooltip="The strike that minimises total option-holder payout at expiry.")
show_strength = input.bool(true, "Wall strength score", group=grpG,
     tooltip="Appends [0-100] to each wall label: how big that strike's net gamma is against the biggest on the board. 100 = the dominant wall. Same conviction number FreeFlow's own extension shows.")
show_regime = input.bool(true, "Gamma regime note", group=grpG,
     tooltip="Adds the dealer gamma regime to the flip label - long gamma (dealers dampen: buy dips / sell rips, mean-revert) vs short gamma (dealers amplify: moves extend).")

grpP = "Span"
span_session = input.bool(true, "Span the session", group=grpP,
     tooltip="Start each level at the first bar of the current trading session (the chart symbol's own session, so 18:00 ET on CME futures) instead of a fixed bar count. Turn off to use the bar count below.")
lines_back   = input.int(60,  "...or start this many bars back", minval=0, maxval=500, group=grpP)
lines_fwd    = input.int(20,  "Extend right of last bar (bars)", minval=0, maxval=200, group=grpP)
extend_right = input.bool(false, "Extend right forever", group=grpP)

// Conversion is done the way FreeFlow's own indicator does it: the cash/ETF the levels came
// from is pulled with request.security and the chart/cash ratio is measured LIVE, then
// smoothed. The generated ratio in the payload is only a fallback now. This matters because
// the futures/cash basis DRIFTS through the session - a ratio frozen at pull time slowly
// walks the levels off, and it degrades to nothing at all if the pull's price lookup failed.
grpX = "Conversion"
preset_select = input.string("NQ / MNQ -> QQQ (ETF)", "Asset preset", options=[
     "Manual Selection", "ES / MES -> SPX (INDEX)", "ES / MES -> SPY (ETF)",
     "NQ / MNQ -> NDX (INDEX)", "NQ / MNQ -> QQQ (ETF)", "GC / MGC -> GLD (ETF)",
     "SI / SIL -> SLV (ETF)", "YM / MYM -> RUT (INDEX)", "YM / MYM -> IWM (ETF)"
     ], group=grpX, tooltip="The cash/ETF the levels were computed from - QQQ for this feed. The chart itself is treated as the futures leg. On a chart of the cash symbol itself no conversion is applied.")
sym_manual    = input.symbol("NASDAQ:QQQ", "Cash / ETF symbol (Manual)", group=grpX)
smoothing     = input.int(100, "Level smoothing", minval=1, maxval=600, group=grpX, tooltip="Bars used to average the chart/cash price ratio. Most accurate on 1m/5m.")
tick_size     = input.float(0.25, "Tick size rounding", minval=0, group=grpX, tooltip="Round converted levels to a valid tick (0.25 for NQ/MNQ, 0.005 for SI). 0 = exact math.")
show_source   = input.bool(true, "Show the cash level in the label", group=grpX, tooltip="Appends the original QQQ strike in brackets, e.g. 'SF Call Wall 31031.00 (748)'.")
ratio_override = input.float(0.0, "Ratio override (0 = measure it live)", minval=0, group=grpX,
     tooltip="Force a chart/cash ratio instead of the measured one. 0 uses the live measurement, falling back to the ratio baked into the payload if the cash symbol can't be loaded.")

grpS = "Style"
show_text      = input.bool(true, "Show labels",  group=grpS)
label_size     = input.string("Small", "Label size", options=["Tiny", "Small", "Normal"], group=grpS)
merge_pct      = input.float(0.08, "Merge labels closer than (% of price)", minval=0, step=0.01, group=grpS,
     tooltip="GEX levels cluster, and different models often land on the SAME strike - two chips then stack into unreadable mush. Any level within this band of one already labelled folds into that label instead ('SF Vol Trigger + OI Vol Trigger'). The lines are still drawn separately, so each model keeps its own colour and style. 0 disables merging.")
show_stamp     = input.bool(false, "Show pull time / stale warning", group=grpS)
stale_min      = input.int(30,  "Warn when older than (minutes)",  minval=1, group=grpS)

// Coloured by ROLE, not by methodology - a call wall reads as resistance and a put wall as
// support whichever model produced it, matching TWB's GEX convention (the acceptance test
// for this data). The METHODOLOGY is carried by line style instead: Signed-Flow solid,
// Settlement-OI dashed, Estimated-OI dotted.
grpC = "Colours"
col_call  = input.color(#f23645, "Call wall (resistance)", group=grpC)
col_put   = input.color(#089981, "Put wall (support)",     group=grpC)
col_flip  = input.color(#2962ff, "Gamma flip",             group=grpC)
col_trig  = input.color(#ff9800, "Vol trigger",            group=grpC)
col_vanna = input.color(#9c27b0, "Vanna",                  group=grpC)
col_charm = input.color(#e0b400, "Charm",                  group=grpC)
col_mp    = input.color(#787b86, "Max pain",               group=grpC)
// Declared LAST on purpose: input ids are positional, so appending here never shifts a
// saved setting. Any FUTURE input goes below this line, never above it.
data_in  = input.text_area(GEN_DATA, "Data (Icarus fills this - do not edit)", group="Data")

lbl_size = label_size == "Tiny" ? size.tiny : label_size == "Normal" ? size.normal : size.small

sym_cash = switch preset_select
    "Manual Selection"          => sym_manual
    "ES / MES -> SPX (INDEX)"   => "SP:SPX"
    "ES / MES -> SPY (ETF)"     => "AMEX:SPY"
    "NQ / MNQ -> NDX (INDEX)"   => "NASDAQ:NDX"
    "NQ / MNQ -> QQQ (ETF)"     => "NASDAQ:QQQ"
    "GC / MGC -> GLD (ETF)"     => "AMEX:GLD"
    "SI / SIL -> SLV (ETF)"     => "AMEX:SLV"
    "YM / MYM -> RUT (INDEX)"   => "TVC:RUT"
    "YM / MYM -> IWM (ETF)"     => "AMEX:IWM"
    => sym_manual

// Extended session on purpose: futures trade overnight while the cash leg does not, and a
// regular-session request would go stale the moment the cash close prints.
cash_close = request.security(ticker.modify(sym_cash, session.extended), timeframe.period, close, barmerge.gaps_on)
// On a chart of the cash symbol itself the levels are already chart prices - ratio 1.
is_cash_chart = str.contains(str.upper(sym_cash), str.upper(syminfo.ticker))
live_ratio = ta.sma(close / cash_close, smoothing)

round_tick(v) => tick_size == 0 ? v : math.round(v / tick_size) * tick_size
show_lvl = not show_walls_only

var line[]  LN = array.new<line>()
var label[] L  = array.new<label>()
// Labels already placed this rebuild, with their prices and accumulated text, so a level
// landing on an already-labelled price folds into that label instead of stacking on it.
var float[]  LY   = array.new<float>()
var label[]  LBL  = array.new<label>()
var string[] LTXT = array.new<string>()

// First bar of the current session. time("D") rolls on the SYMBOL's own session boundary,
// so this is 18:00 ET on CME futures and 09:30 on cash - no session string to get wrong.
var int sess_start = bar_index
if ta.change(time("D")) != 0
    sess_start := bar_index

// One level: a horizontal line + right-edge label, only when the field parsed to a real
// number (an empty field, e.g. from an unavailable/calibrating methodology, parses to na
// and is simply skipped - never drawn as a level of zero).
f_level(x1, x2, price, ratio, col, name, sty, wid, show) =>
    if show and not na(price)
        px = round_tick(price * ratio)
        array.push(LN, line.new(x1, px, x2, px, xloc=xloc.bar_index, extend=extend_right ? extend.right : extend.none, color=col, width=wid, style=sty))
        if show_text
            // Different methodologies routinely agree on a strike (both vol triggers here
            // are the same number). Two chips at one price overlap into mush, and nudging
            // them apart by a bar count only works at one zoom - so fold the name into the
            // label that's already there instead. The LINES stay separate, so each model
            // keeps its own colour and style.
            gap = px * merge_pct / 100.0
            hit = -1
            if merge_pct > 0
                for i = 0 to math.max(array.size(LY) - 1, 0)
                    if array.size(LY) > i and math.abs(array.get(LY, i) - px) <= gap
                        hit := i
                        break
            src = show_source ? "  (" + str.tostring(price, "#.##") + ")" : ""
            if hit >= 0
                merged = array.get(LTXT, hit) + " + " + name
                array.set(LTXT, hit, merged)
                label.set_text(array.get(LBL, hit), merged + "  " + str.tostring(px, format.mintick) + src)
            else
                lb = label.new(x2, px, name + "  " + str.tostring(px, format.mintick) + src, xloc=xloc.bar_index, style=label.style_label_left, color=color.new(col, 88), textcolor=col, size=lbl_size)
                array.push(LY, px)
                array.push(LBL, lb)
                array.push(LTXT, name)
                array.push(L, lb)

// One methodology's whole set of levels. Fields 5-8 (max pain, the two strength scores and
// the gamma regime) are only read when the payload actually carries them, so an older
// snapshot still draws the levels it does have rather than erroring.
f_model(x1, x2, seg, ratio, prefix, sty, show) =>
    if show and array.size(seg) >= 5
        cs = array.size(seg) >= 7 ? array.get(seg, 6) : ""
        ps = array.size(seg) >= 8 ? array.get(seg, 7) : ""
        rg = array.size(seg) >= 9 ? array.get(seg, 8) : ""
        ctag = show_strength and cs != "" ? "  [" + cs + "]" : ""
        ptag = show_strength and ps != "" ? "  [" + ps + "]" : ""
        rtag = show_regime and rg != "" ? (rg == "LONG" ? "  · Long-γ: dampen" : "  · Short-γ: amplify") : ""
        f_level(x1, x2, str.tonumber(array.get(seg, 1)), ratio, col_call, prefix + " Call Wall" + ctag,   sty, 2, true)
        f_level(x1, x2, str.tonumber(array.get(seg, 2)), ratio, col_put,  prefix + " Put Wall" + ptag,    sty, 2, true)
        f_level(x1, x2, str.tonumber(array.get(seg, 3)), ratio, col_flip, prefix + " Gamma Flip" + rtag,  sty, 1, show_lvl)
        f_level(x1, x2, str.tonumber(array.get(seg, 4)), ratio, col_trig, prefix + " Vol Trigger",        sty, 1, show_lvl)
        if array.size(seg) >= 6
            f_level(x1, x2, str.tonumber(array.get(seg, 5)), ratio, col_mp, prefix + " Max Pain", sty, 1, show_lvl and show_maxpain)

// Wiped and rebuilt on the last bar only, so history accumulates nothing.
if barstate.islast
    for ln in LN
        line.delete(ln)
    array.clear(LN)
    for l in L
        label.delete(l)
    array.clear(L)
    array.clear(LY)
    array.clear(LBL)
    array.clear(LTXT)

    parts = str.split(data_in, "|")
    if array.size(parts) >= 8
        gen_label = array.get(parts, 0)
        gen_ts    = str.tonumber(array.get(parts, 1))
        gen_ratio = str.tonumber(array.get(parts, 2))
        // Live measurement first, the payload's frozen ratio only as a fallback when the
        // cash symbol can't be loaded (and 1.0 when the chart IS the cash symbol).
        ratio = ratio_override > 0 ? ratio_override : is_cash_chart ? 1.0 : not na(live_ratio) and live_ratio > 0 ? live_ratio : gen_ratio

        x1 = span_session ? sess_start : bar_index - lines_back
        x2 = bar_index + lines_fwd

        // Walls carry the weight (width 2) - the flip, trigger and max pain are context.
        f_model(x1, x2, str.split(array.get(parts, 3), ","), ratio, "SF",  line.style_solid,  show_sf)
        f_model(x1, x2, str.split(array.get(parts, 4), ","), ratio, "OI",  line.style_dashed, show_oi)
        f_model(x1, x2, str.split(array.get(parts, 5), ","), ratio, "EOI", line.style_dotted, show_eoi)

        vanna = str.split(array.get(parts, 6), ",")
        if array.size(vanna) >= 3
            f_level(x1, x2, str.tonumber(array.get(vanna, 0)), ratio, col_vanna, "Vanna Call Wall", line.style_solid,  2, show_vanna)
            f_level(x1, x2, str.tonumber(array.get(vanna, 1)), ratio, col_vanna, "Vanna Put Wall",  line.style_solid,  2, show_vanna)
            f_level(x1, x2, str.tonumber(array.get(vanna, 2)), ratio, col_vanna, "Vanna Flip",      line.style_dotted, 1, show_vanna and show_lvl)

        charm = str.split(array.get(parts, 7), ",")
        if array.size(charm) >= 3
            f_level(x1, x2, str.tonumber(array.get(charm, 0)), ratio, col_charm, "Charm + Zone", line.style_solid,  2, show_charm)
            f_level(x1, x2, str.tonumber(array.get(charm, 1)), ratio, col_charm, "Charm - Zone", line.style_solid,  2, show_charm)
            f_level(x1, x2, str.tonumber(array.get(charm, 2)), ratio, col_charm, "Charm Flip",   line.style_dotted, 1, show_charm and show_lvl)

        if show_stamp
            age_min = (timenow - gen_ts) / 60000.0
            is_stale = age_min > stale_min
            stamp = gen_label + (is_stale ? "\\nSTALE: " + str.tostring(age_min, "#") + " min old" : "")
            array.push(L, label.new(x2, na(close) ? 0 : close, stamp, xloc=xloc.bar_index, style=label.style_label_down, color=color.new(is_stale ? color.orange : color.gray, 40), textcolor=color.white, size=size.small))
"""

# Pine strings cap at 4,096 characters, and the whole snapshot travels as one string.
MAX_DATA_CHARS = 4000


def _wall_strength(gex, strike, side):
    """0-100: how big this wall is against the biggest wall ON ITS OWN SIDE.

    This is the [57] / [100] conviction number FreeFlow's own browser extension puts on
    each wall. Computed from the per-strike rows already in the snapshot - no extra API
    call, no extra rate-limit budget.

    Normalised per side, not against the whole board, because call gamma routinely dwarfs
    put gamma: a board-wide denominator scores every put wall near zero even when it is the
    dominant put on the chain. Checked against FreeFlow's own extension, which scored the
    735 put wall [100] while a board-wide denominator gave it 22.
    """
    rows = (gex or {}).get("by_strike") or (gex or {}).get("rows") or []
    key = "call_gex" if side == "call" else "put_gex"
    if not rows or strike is None:
        return ""
    peak = max((abs(r.get(key) or 0) for r in rows), default=0)
    if not peak:
        return ""
    here = next((abs(r.get(key) or 0) for r in rows if r.get("strike") == strike), None)
    if here is None:
        return ""
    return f"{round(here / peak * 100)}"


def _gex_field(gex):
    """status,callWall,putWall,gammaFlip,volTrigger,maxPain,callStrength,putStrength,regime

    Levels come through blank (not zero) when the methodology isn't healthy, so the Pine
    side never draws a level that doesn't exist. Fields 5-8 were APPENDED after the first
    release: Pine reads 0-4 and only reaches for the rest when they're present, so an older
    copy of the script on a chart keeps working against a newer payload.
    """
    g = gex or {}
    status = g.get("status") or "unavailable"
    healthy = status not in ("unavailable", "calibrating")

    def level(key):
        v = g.get(key)
        return f"{v:g}" if healthy and v is not None else ""

    call_strike, put_strike = (g.get("call_wall"), g.get("put_wall")) if healthy else (None, None)
    # Dealers long gamma dampen moves (buy dips / sell rips); short gamma amplifies them.
    total = g.get("total_gex")
    regime = "" if not healthy or total is None else ("LONG" if total > 0 else "SHORT")
    return ",".join([
        status,
        level("call_wall"),
        level("put_wall"),
        level("gamma_flip"),
        level("vol_trigger"),
        level("max_pain"),
        _wall_strength(g, call_strike, "call") if healthy else "",
        _wall_strength(g, put_strike, "put") if healthy else "",
        regime,
    ])


def _point_field(*points):
    """One or more {strike, value} points (or a bare strike int for `flip`) -> CSV of
    just the strike - the Pine side only draws levels, the magnitude stays informational."""
    out = []
    for p in points:
        if p is None:
            out.append("")
        elif isinstance(p, dict):
            strike = p.get("strike")
            out.append(f"{strike:g}" if strike is not None else "")
        else:
            out.append(f"{p:g}")
    return ",".join(out)


def build_gex_data(gex, nq=None, now=None):
    """The one-string snapshot the Pine script parses: label, timing, then one CSV
    segment per group (see PINE_TEMPLATE's field comment for the exact layout)."""
    if not gex.get("ok"):
        raise ValueError(f"Cannot export a failed pull: {gex.get('error')}")
    now = now or datetime.now(CT)
    ratio = (nq / gex["spot"]) if nq and gex.get("spot") else 0.0
    label = f"{gex['underlying']} GEX {gex['exp']} - pulled {now.strftime('%-I:%M %p CT')}"
    vanna = gex.get("vanna_walls") or {}
    charm = gex.get("charm_zones") or {}
    fields = [
        label,
        str(int(now.timestamp() * 1000)),
        f"{ratio:.4f}",
        _gex_field(gex.get("sf_gex")),
        _gex_field(gex.get("oi_gex")),
        _gex_field(gex.get("eoi_gex")),
        _point_field(vanna.get("call_wall"), vanna.get("put_wall"), vanna.get("flip")),
        _point_field(charm.get("positive_zone"), charm.get("negative_zone"), charm.get("flip")),
    ]
    data = "|".join(fields)
    if len(data) > MAX_DATA_CHARS:
        # Headline levels only - this payload has no per-strike rows to trim like the
        # ladder's does, so hitting the cap would mean something is very wrong upstream.
        raise ValueError(f"GEX data payload unexpectedly large ({len(data)} chars)")
    return data


def build_gex_pine(gex, nq=None, now=None):
    """Pine source for one GEX snapshot (the dict freeflow.get_gex_walls() returns)."""
    return PINE_TEMPLATE.replace("//<<DATA>>", f'GEN_DATA = "{build_gex_data(gex, nq, now)}"')


def export_gex_pine(gex, nq=None):
    """Write the current + dated .pine files and put the source on the clipboard."""
    now = datetime.now(CT)
    source = build_gex_pine(gex, nq, now)
    run_dir = RUNS_DIR / f"{now.strftime('%Y-%m-%d_%H%M%S')}_pine"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / CURRENT_PINE_PATH.name).write_text(source)
    CURRENT_PINE_PATH.write_text(source)
    copied = True
    try:
        subprocess.run(["pbcopy"], input=source.encode(), check=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        copied = False
    return {"path": str(CURRENT_PINE_PATH), "copied": copied}
